// Code generated by "stringer -type=SchemaNestingMode -trimprefix Schema"; DO NOT EDIT.

package tfsdk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[schemaNestingInvalid-0]
	_ = x[SchemaNestingSingle-1]
	_ = x[SchemaNestingList-2]
	_ = x[SchemaNestingMap-3]
	_ = x[SchemaNestingSet-4]
}

const _SchemaNestingMode_name = "schemaNestingInvalidNestingSingleNestingListNestingMapNestingSet"

var _SchemaNestingMode_index = [...]uint8{0, 20, 33, 44, 54, 64}

func (i SchemaNestingMode) String() string {
	if i < 0 || i >= SchemaNestingMode(len(_SchemaNestingMode_index)-1) {
		return "SchemaNestingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SchemaNestingMode_name[_SchemaNestingMode_index[i]:_SchemaNestingMode_index[i+1]]
}
